<?php
// Define Request ID Prefix (To be added to the int that is the mapped request ID
const REQUEST_ID_PREFIX = 900;

// Defaults
const IMPACT_COLUMN_DEFAULT = 1;
const URGENCY_COLUMN_DEFAULT = 1;
const CLIENT_NAME_COLUMN_DEFAULT = 'Organization';
const SITE_NAME_COLUMN_DEFAULT = 'Requester domain';
const USERNAME_COLUMN_DEFAULT = 'Requester';
const SUMMARY_COLUMN_DEFAULT = 'Subject';
const DETAILS_COLUMN_DEFAULT = 'Description';
const DATE_OCCURRED_COLUMN_DEFAULT = 'Created at';
const CATEGORY_COLUMN_DEFAULT = 'Account Administration';
const CATEGORY1_COLUMN_DEFAULT = 'Account Administration';
const CATEGORY2_COLUMN_DEFAULT = 'Group';
const STATUS_COLUMN_DEFAULT = 'Status';
const ASSIGNED_TO_COLUMN_DEFAULT = 'Assignee';
const TEAM_COLUMN_DEFAULT = 'NA';
const REQUEST_TYPE_COLUMN_DEFAULT = 'Ticket type';

const PRIORITY_COLUMN_DEFAULT = 'Priority';
const SLA_COLUMN_DEFAULT = 'Our Example SLA 1';
const OPPORTUNITY_EMAIL_ADDRESS_COLUMN_DEFAULT = '';
const OPPORTUNITY_ADDRESS1_COLUMN_DEFAULT = '';
const OPPORTUNITY_ADDRESS2_COLUMN_DEFAULT = '';
const OPPORTUNITY_ADDRESS3_COLUMN_DEFAULT = '';
const OPPORTUNITY_ADDRESS4_COLUMN_DEFAULT = '';
const OPPORTUNITY_POSTAL_CODE_COLUMN_DEFAULT = '';
const OPPORTUNITY_VALUE_COLUMN_DEFAULT = '';
const OPPORTUNITY_CONVERSION_PROBABILITY_COLUMN_DEFAULT = '';